In [1]:
# !pip install joblib

In [2]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
import pandas as pd

plt.style.use('fivethirtyeight')

In [3]:
class Perceptron :
    def __init__(self, eta: float= None, epochs:int= None):
        self.weights = np.random.randn(3)* 1e-4
        self.eta = eta # learning rate
        self.epochs = epochs # iterations
    
    def _z_outcome(self, inputs, weights):
        return np.dot(inputs, weights)
    
    def activation_function(self, z):
        return np.where(z > 0, 1, 0)
        
    def fit(self, X, y):
        self.X = X
        self.y = y
        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
        print(f'X with bias: \n{X_with_bias}')
        
        for epoch in range(self.epochs):
            print("--"*10)
            print(f"For epoch >> {epoch+1} ")
            print("--"*10)
            
            z = self._z_outcome(X_with_bias, self.weights)
            y_hat = self.activation_function(z)
            print(f"Predicted value after the forward pass: \n{y_hat}")
            
            self.error = self.y - y_hat
            print(f"Error at every step : \n{self.error}")
            
            self.weights = self.weights + self.eta* np.dot(X_with_bias.T, self.error)
            print(f"Updated weights after  epoch : {(epoch +1)/self.epochs} \n{self.weights}")
            print(f"##"*10)
         
    def predict(self, X):
        X_with_bias = np.c_[X, -np.ones((len(X), 1))]
        z = self._z_outcome(X_with_bias, self.weights)
        return self.activation_function(z)
    

        

In [4]:
OR = {
    "x1": [0, 0, 1, 1],
    "x2": [0, 1, 0, 1], 
    "y" : [0, 1, 1, 1]
}
df_OR = pd.DataFrame(OR)
df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [5]:
def prepare_data(df, target_col = "y"):
    X = df.drop(target_col, axis = 1)
    y = df[target_col]
    
    return X, y 

In [6]:
X, y = prepare_data(df_OR)
print(X)
print(y)


   x1  x2
0   0   0
1   0   1
2   1   0
3   1   1
0    0
1    1
2    1
3    1
Name: y, dtype: int64


In [7]:
ETA = 0.1
EPOCHS = 10
model_or = Perceptron(eta = ETA, epochs = EPOCHS)
model_or.fit(X, y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
For epoch >> 1 
--------------------
Predicted value after the forward pass: 
[1 0 0 0]
Error at every step : 
0   -1
1    1
2    1
3    1
Name: y, dtype: int64
Updated weights after  epoch : 0.1 
[ 0.19990911  0.19991715 -0.20002316]
####################
--------------------
For epoch >> 2 
--------------------
Predicted value after the forward pass: 
[1 1 1 1]
Error at every step : 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights after  epoch : 0.2 
[ 0.19990911  0.19991715 -0.10002316]
####################
--------------------
For epoch >> 3 
--------------------
Predicted value after the forward pass: 
[1 1 1 1]
Error at every step : 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights after  epoch : 0.3 
[ 1.99909111e-01  1.99917148e-01 -2.31600759e-05]
####################
--------------------
For epoch >> 4 
--------------------
Predicted value after th

In [8]:
model_or.predict(X)

array([0, 1, 1, 1])

In [10]:
AND = {
    "x1": [0, 0, 1, 1],
    "x2": [0, 1, 0, 1], 
    "y" : [0, 0, 0, 1]
}
df_AND = pd.DataFrame(AND)
df_AND



x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [11]:
X, y = prepare_data(df_AND)
print(X)
print(y)

   x1  x2
0   0   0
1   0   1
2   1   0
3   1   1
0    0
1    0
2    0
3    1
Name: y, dtype: int64


In [12]:
ETA = 0.1
EPOCHS = 10
model_or = Perceptron(eta = ETA, epochs = EPOCHS)
model_or.fit(X, y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
For epoch >> 1 
--------------------
Predicted value after the forward pass: 
[1 1 1 1]
Error at every step : 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated weights after  epoch : 0.1 
[-0.10003683 -0.09995148  0.29992641]
####################
--------------------
For epoch >> 2 
--------------------
Predicted value after the forward pass: 
[0 0 0 0]
Error at every step : 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights after  epoch : 0.2 
[-3.68301426e-05  4.85203827e-05  1.99926410e-01]
####################
--------------------
For epoch >> 3 
--------------------
Predicted value after the forward pass: 
[0 0 0 0]
Error at every step : 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights after  epoch : 0.3 
[0.09996317 0.10004852 0.09992641]
####################
--------------------
For epoch >> 4 
--------------------
Predicted value after the f

In [13]:
model_or.predict(X)

array([0, 0, 0, 1])